version: '3.8'

services:
  bilingual-tutor:
    build: .
    container_name: chat-genv
    ports:
      - "8501:8501"
    env_file: 
      - .env  
    environment:
      - API_KEY=${API_KEY}  
    volumes:
      - .:/app
    restart: unless-stopped
    devices: 
      - "/dev/snd:/dev/snd"